name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          echo "Dependencies installed successfully"

      - name: Create deployment package
        run: |
          mkdir deployment
          cp lamda-func-one.py deployment/
          cp -r venv/lib/python3.8/site-packages/* deployment/
          cd deployment
          zip -r lambda_function.zip .
          echo "ZIP file created successfully"

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name myFirstFuncTest \
            --zip-file fileb://deployment/lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2 # Replace with your desired region

      - name: Done with the flow
        run: |
          # Your AWS CLI command here
          echo "Lambda function deployed successfully"
